# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20191106_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', '\u8349\u7a3f'), ('published', '\u5df2\u53d1\u5e03')], default='draft', max_length=32, verbose_name='\u72b6\u6001'),
        ),
    ]
