# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191107_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(choices=[('html', '\u5bcc\u6587\u672c'), ('markdown', 'Markdown')], default='html', max_length=32, verbose_name='\u6587\u7ae0\u683c\u5f0f\u7c7b\u578b'),
        ),
    ]
