# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_disabled',
            field=models.BooleanField(default=False, verbose_name='\u8bc4\u8bba\u5f00\u5173'),
        ),
    ]
