# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-15 07:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20191104_0405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('last_dt', models.DateTimeField(auto_now=True, verbose_name='\u6700\u540e\u66f4\u65b0\u65f6\u95f4')),
                ('name', models.CharField(max_length=64, verbose_name='\u56fe\u7247\u540d')),
                ('type', models.CharField(choices=[('cover', '\u6587\u7ae0\u5c01\u9762'), ('other', '\u5176\u4ed6')], default='other', max_length=32, verbose_name='\u56fe\u7247\u7c7b\u578b')),
                ('address', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u5730\u5740')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User', verbose_name='\u6240\u5c5e\u7528\u6237')),
            ],
            options={
                'ordering': ['-create_dt'],
                'abstract': False,
                'db_table': 'tb_image',
            },
        ),
    ]
