# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-22 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('cover', '\u6587\u7ae0\u5c01\u9762'), ('avatar', '\u5934\u50cf'), ('other', '\u5176\u4ed6')], default='other', max_length=32, verbose_name='\u56fe\u7247\u7c7b\u578b'),
        ),
    ]
