# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='http://oss.iclould.xyz/avatar/admin.jpg', max_length=256, verbose_name='\u5934\u50cf'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='rafa_im@163.com', max_length=254, verbose_name='\u5934\u50cf'),
        ),
    ]
