# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-04 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20191104_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='\u5934\u50cf'),
        ),
    ]
